// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiXDk_Hj7fAJHEJlVeZYBxiz6UMUiTtuU',
    appId: '1:596562529470:web:4475dc725d3f1fec37e2ef',
    messagingSenderId: '596562529470',
    projectId: 'campus-hiring-3939f',
    authDomain: 'campus-hiring-3939f.firebaseapp.com',
    storageBucket: 'campus-hiring-3939f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChj6riz7_EwI3Q4ZX55VphC1KDp-MiKDE',
    appId: '1:596562529470:android:a199d3b57ef19a3f37e2ef',
    messagingSenderId: '596562529470',
    projectId: 'campus-hiring-3939f',
    storageBucket: 'campus-hiring-3939f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnjjM2FjwEI4pFlHG4qcAu2ASQaMd4gqw',
    appId: '1:596562529470:ios:b117cc5867e5627037e2ef',
    messagingSenderId: '596562529470',
    projectId: 'campus-hiring-3939f',
    storageBucket: 'campus-hiring-3939f.appspot.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnjjM2FjwEI4pFlHG4qcAu2ASQaMd4gqw',
    appId: '1:596562529470:ios:b117cc5867e5627037e2ef',
    messagingSenderId: '596562529470',
    projectId: 'campus-hiring-3939f',
    storageBucket: 'campus-hiring-3939f.appspot.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiXDk_Hj7fAJHEJlVeZYBxiz6UMUiTtuU',
    appId: '1:596562529470:web:5580df02c9533fe837e2ef',
    messagingSenderId: '596562529470',
    projectId: 'campus-hiring-3939f',
    authDomain: 'campus-hiring-3939f.firebaseapp.com',
    storageBucket: 'campus-hiring-3939f.appspot.com',
  );
}
